# Generated by Django 4.1 on 2022-09-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cuenta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
